name: Build

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      - name: xcodebuild
        run: xcodebuild -scheme Rideau -sdk iphoneos CODE_SIGNING_ALLOWED=NO
